name: CI

on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/Values.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run test
        run: ./gradlew test --stacktrace
